function FinalPlot(TOUT,YOUT)
%% FinalPlot è una funzione che permette di visualizzare le varibili durante la traiettoria
% INPUT
% - YOUT: Vettore d'uscita della ode con angoli di eulero
% - TOUT: Tempo  rispetto a YOUT
% - BoomInfo: Struct con le informazioni geometriche del boomerang
% OUTPUT:
% - Grafico
linecolors={'r' 'y' 'c' 'g' 'b' 'k'};
[handles]=plotNy(TOUT(:),YOUT(:,1)*180/pi,1,...
    TOUT(:),YOUT(:,2)*180/pi,1,...
    TOUT(:),YOUT(:,3)*180/pi,1,...
    TOUT(:),YOUT(:,6),2,...
    TOUT(:),YOUT(:,4),2,...
    TOUT(:),YOUT(:,5),2,...
    TOUT(:),YOUT(:,10),3,...
    TOUT(:),YOUT(:,11),3,...
    TOUT(:),YOUT(:,12),3,...
    'YAxisLabels',{ 'Angolo [°]' 'Velocità Angolare [rad/s]' 'Posizione [m]'},...
    'Linewidth',1,...
    'XLim',[0,TOUT(end)],...
    'XAxisLabel','time[s]',...
    'TitleStr','Lancio Finale',...
    'FontSize',10,...
    'LegendString',{'Theta' 'Phi' 'Psi' 'r' 'p' 'q' 'x' 'y' 'z'});
grid on
end

